### ISSUE TITLE
80-frontend-crud-PersonalSchedulesAdmin

### ISSUE THREAD

**Issue by bobhe9606** [ucsb-cs156-w22/team04-w22-7pm-courses#18]
Front End Crud personal schedules (admin)

I recommend breaking this issue up into multiple issues.

In this issue you will create front end components for
admins to manipulate personal schedule objects.

You'll need an suitable menu on the menu bar that shows up only
for admins (or you can add options to the admin menu)

You'll need a table to display personal schedules, with buttons for edit and delete; or just reuse the code for the component for regular users; but add an extra column for admins showing the user that "owns" the personal schedule item".

Also reuse the form for editing.

It is not necessary to allow admins to create personal schedules for other users.

It should NOT be permitted to change the owner ship of a personal schedule; the user id should be not editable.

Add your own ACs, and break this into multiple issues as needed.

**Comment by edisonnchen** [comment]
Split into different issues
