### ISSUE TITLE
Implement a Level Selector Component

### ISSUE THREAD

**Issue by noahzlutz** [ucsb-cs156-w22/team04-w22-7pm-courses#7]
There is already component that allows you to select a quarter from a dropdown menu; it appears in the Storybook and has full test coverage.

Add an additional component that allows you to select a level (UG-lower div, UG-upper div, grad, all). The levels can be hard coded.

You can use code from the S21 proj-ucsb-courses-search as a model.

DEFINE SUITABLE ACCEPTANCE CRITERIA

**Comment by ericxu002** [comment]
duplicate of issue #8
